/**
 * defaultComponents — seed catalog of reusable invitation design components.
 *
 * Each component has:
 *   id               — stable identifier
 *   name             — display name
 *   type             — text | image | separator | icon
 *   category         — text | decorative | icon | separator
 *   defaultHtml      — default HTML snippet
 *   defaultCss       — optional scoped CSS
 *   imageUrl         — URL for image/icon components (null for text)
 *   colorizable      — whether palette colors can be applied
 *   allowedPositions — valid placement positions
 *   isDefault        — true = shipped with platform
 */

module.exports = [
  // ── Text blocks ──────────────────────────────────────────────────────────
  {
    id: 'comp-title',
    name: 'Title Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<h1 class="inv-title" style="color:{color1}">{eventName}</h1>',
    defaultCss: '.inv-title { font-size: 2.5rem; font-weight: 700; text-align: center; font-family: serif; letter-spacing: 0.05em; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-subtitle',
    name: 'Subtitle Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<p class="inv-subtitle" style="color:{color2}">{eventSubtitle}</p>',
    defaultCss: '.inv-subtitle { font-size: 1.25rem; text-align: center; font-style: italic; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-free-text',
    name: 'Free Text Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<p class="inv-text" style="color:{color4}">{freeText}</p>',
    defaultCss: '.inv-text { font-size: 1rem; text-align: center; line-height: 1.7; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-date',
    name: 'Date Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<div class="inv-date" style="color:{color1}"><span class="inv-date__icon">📅</span> {eventDate}</div>',
    defaultCss: '.inv-date { font-size: 1.1rem; text-align: center; font-weight: 600; margin: 0.5rem 0; } .inv-date__icon { margin-right: 0.4rem; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-time',
    name: 'Time Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<div class="inv-time" style="color:{color2}"><span class="inv-time__icon">🕐</span> {eventTime}</div>',
    defaultCss: '.inv-time { font-size: 1.1rem; text-align: center; font-weight: 600; margin: 0.5rem 0; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-location',
    name: 'Location Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<div class="inv-location" style="color:{color1}"><span>📍</span> {eventLocation}</div>',
    defaultCss: '.inv-location { font-size: 1.1rem; text-align: center; font-weight: 600; margin: 0.5rem 0; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-address',
    name: 'Address Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<p class="inv-address" style="color:{color4}">{eventAddress}</p>',
    defaultCss: '.inv-address { font-size: 0.9rem; text-align: center; opacity: 0.8; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-guest-name',
    name: 'Guest Name Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<p class="inv-guest-name" style="color:{color2}">Dear <strong>{guestName}</strong>,</p>',
    defaultCss: '.inv-guest-name { font-size: 1.15rem; text-align: center; font-style: italic; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-seats',
    name: 'Seats Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<p class="inv-seats" style="color:{color4}">🎟 Reserved seats: <strong>{guestSeats}</strong></p>',
    defaultCss: '.inv-seats { font-size: 1rem; text-align: center; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-recommendations',
    name: 'Recommendations Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<p class="inv-recommendations" style="color:{color4}">{recommendations}</p>',
    defaultCss: '.inv-recommendations { font-size: 0.9rem; text-align: center; opacity: 0.85; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-dress-code',
    name: 'Dress Code Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<p class="inv-dress-code" style="color:{color2}">👗 Dress code: <strong>{dressCode}</strong></p>',
    defaultCss: '.inv-dress-code { font-size: 1rem; text-align: center; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-gift-suggestions',
    name: 'Gift Suggestions Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<p class="inv-gifts" style="color:{color4}">🎁 {giftSuggestions}</p>',
    defaultCss: '.inv-gifts { font-size: 0.95rem; text-align: center; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-adults-only',
    name: '"Adults Only" Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<p class="inv-adults-only" style="color:{color1}">🔞 This is an adults-only event.</p>',
    defaultCss: '.inv-adults-only { font-size: 0.9rem; text-align: center; font-weight: 600; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-no-pets',
    name: '"No Pets / No Children" Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<p class="inv-no-pets" style="color:{color1}">🚫 No pets or children under 12.</p>',
    defaultCss: '.inv-no-pets { font-size: 0.9rem; text-align: center; font-weight: 600; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-custom-notes',
    name: 'Custom Notes Block',
    type: 'text',
    category: 'text',
    defaultHtml: '<p class="inv-custom-notes" style="color:{color4}"><em>{customNotes}</em></p>',
    defaultCss: '.inv-custom-notes { font-size: 0.9rem; text-align: center; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },

  // ── Separators ───────────────────────────────────────────────────────────
  {
    id: 'comp-sep-line',
    name: 'Line Separator',
    type: 'separator',
    category: 'separator',
    defaultHtml: '<hr class="inv-sep-line" style="border-color:{color3}"/>',
    defaultCss: '.inv-sep-line { width: 60%; margin: 1rem auto; border-top-width: 1px; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-sep-diamond',
    name: 'Diamond Separator',
    type: 'separator',
    category: 'separator',
    defaultHtml: '<div class="inv-sep-diamond" style="color:{color2}">◆ ◆ ◆</div>',
    defaultCss: '.inv-sep-diamond { text-align: center; letter-spacing: 0.5rem; font-size: 0.75rem; margin: 0.75rem 0; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-sep-floral',
    name: 'Floral Separator',
    type: 'separator',
    category: 'separator',
    defaultHtml: '<div class="inv-sep-floral" style="color:{color2}">❧ ── ✿ ── ❧</div>',
    defaultCss: '.inv-sep-floral { text-align: center; font-size: 1rem; margin: 0.75rem 0; letter-spacing: 0.3rem; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },

  // ── Icons ────────────────────────────────────────────────────────────────
  {
    id: 'comp-icon-calendar',
    name: 'Calendar Icon',
    type: 'icon',
    category: 'icon',
    defaultHtml: '<span class="inv-icon" style="color:{color1}">📅</span>',
    defaultCss: '.inv-icon { font-size: 1.5rem; display: inline-block; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-icon-heart',
    name: 'Heart Icon',
    type: 'icon',
    category: 'icon',
    defaultHtml: '<span class="inv-icon-heart" style="color:{color1}">♥</span>',
    defaultCss: '.inv-icon-heart { font-size: 2rem; display: block; text-align: center; margin: 0.5rem 0; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-icon-ring',
    name: 'Ring Icon',
    type: 'icon',
    category: 'icon',
    defaultHtml: '<span class="inv-icon" style="color:{color1}">💍</span>',
    defaultCss: '.inv-icon { font-size: 1.5rem; display: inline-block; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-icon-gift',
    name: 'Gift Box Icon',
    type: 'icon',
    category: 'icon',
    defaultHtml: '<span class="inv-icon" style="color:{color1}">🎁</span>',
    defaultCss: '.inv-icon { font-size: 1.5rem; display: inline-block; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-icon-mappin',
    name: 'Map Pin Icon',
    type: 'icon',
    category: 'icon',
    defaultHtml: '<span class="inv-icon" style="color:{color1}">📍</span>',
    defaultCss: '.inv-icon { font-size: 1.5rem; display: inline-block; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },

  // ── Decorative corners / borders ─────────────────────────────────────────
  {
    id: 'comp-corner-tl',
    name: 'Floral Corner (Top-Left)',
    type: 'image',
    category: 'decorative',
    defaultHtml: '<div class="inv-corner-tl" style="color:{color2}">❀</div>',
    defaultCss: '.inv-corner-tl { position: absolute; top: 0.5rem; left: 0.5rem; font-size: 3rem; opacity: 0.6; pointer-events: none; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['top-left'],
    isDefault: true,
  },
  {
    id: 'comp-corner-tr',
    name: 'Floral Corner (Top-Right)',
    type: 'image',
    category: 'decorative',
    defaultHtml: '<div class="inv-corner-tr" style="color:{color2}">❀</div>',
    defaultCss: '.inv-corner-tr { position: absolute; top: 0.5rem; right: 0.5rem; font-size: 3rem; opacity: 0.6; pointer-events: none; transform: scaleX(-1); }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['top-right'],
    isDefault: true,
  },
  {
    id: 'comp-corner-bl',
    name: 'Floral Corner (Bottom-Left)',
    type: 'image',
    category: 'decorative',
    defaultHtml: '<div class="inv-corner-bl" style="color:{color2}">❀</div>',
    defaultCss: '.inv-corner-bl { position: absolute; bottom: 0.5rem; left: 0.5rem; font-size: 3rem; opacity: 0.6; pointer-events: none; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['bottom-left'],
    isDefault: true,
  },
  {
    id: 'comp-corner-br',
    name: 'Floral Corner (Bottom-Right)',
    type: 'image',
    category: 'decorative',
    defaultHtml: '<div class="inv-corner-br" style="color:{color2}">❀</div>',
    defaultCss: '.inv-corner-br { position: absolute; bottom: 0.5rem; right: 0.5rem; font-size: 3rem; opacity: 0.6; pointer-events: none; transform: scale(-1, 1); }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['bottom-right'],
    isDefault: true,
  },
  {
    id: 'comp-border-gold',
    name: 'Gold Border',
    type: 'image',
    category: 'decorative',
    defaultHtml: '<div class="inv-border-gold" style="border-color:{color1}"></div>',
    defaultCss: '.inv-border-gold { position: absolute; inset: 0.75rem; border: 2px solid; pointer-events: none; border-radius: 2px; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
  {
    id: 'comp-border-double',
    name: 'Double Border',
    type: 'image',
    category: 'decorative',
    defaultHtml: '<div class="inv-border-double" style="border-color:{color3}; outline-color:{color1}"></div>',
    defaultCss: '.inv-border-double { position: absolute; inset: 0.5rem; border: 3px double; pointer-events: none; }',
    imageUrl: null,
    colorizable: true,
    allowedPositions: ['center'],
    isDefault: true,
  },
]
